# Generated by Django 6.0 on 2026-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=20)),
                ('create_at', models.TimeField()),
            ],
        ),
    ]
