# Generated by Django 6.0 on 2026-07-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_course',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=20)),
                ('fees', models.IntegerField()),
                ('create_at', models.TimeField()),
            ],
        ),
    ]
