# Generated by Django 6.0 on 2026-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tbl_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_student',
            name='aadhar_no',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='emailaddress',
            field=models.EmailField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='password',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
