# Generated by Django 6.0 on 2026-07-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_tbl_student_aadhar_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_student',
            old_name='session',
            new_name='Session',
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='emailaddress',
            field=models.EmailField(max_length=225, null=True, unique=True),
        ),
    ]
