# Generated by Django 6.0 on 2026-07-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_session_tbl_student_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_student',
            name='aadhar_no',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='emailaddress',
            field=models.EmailField(max_length=225, null=True),
        ),
    ]
