# Generated by Django 6.0 on 2026-07-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tbl_payment_tbl_student_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_student',
            name='step1_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbl_student',
            name='step2_completed',
            field=models.BooleanField(default=False),
        ),
    ]
